/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * status_item.java
 *
 * Created on Sep 19, 2010, 10:18:01 AM
 */
package twitterclient;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import winterwell.jtwitter.Twitter.Status;

/**
 *
 * @author samup4web
 */
public class status_item extends javax.swing.JPanel implements ListCellRenderer {

    /** Creates new form status_item */
    public status_item() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        status_item_txt = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 2));

        status_item_txt.setBackground(new java.awt.Color(241, 237, 237));
        status_item_txt.setColumns(20);
        status_item_txt.setRows(5);
        jScrollPane1.setViewportView(status_item_txt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea status_item_txt;
    // End of variables declaration//GEN-END:variables

    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        //throw new UnsupportedOperationException("Not supported yet.");
        Status st = (Status) value;
        status_item_txt.setText(st.getText());

        return this;

    }
}
