/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TwitterClient.java
 *
 * Created on Sep 17, 2010, 3:27:42 PM
 */
package twitterclient;

import java.awt.BorderLayout;
import java.net.MalformedURLException;
import java.net.URI;
import java.util.Iterator;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import winterwell.jtwitter.Twitter;
import winterwell.jtwitter.Twitter.Status;
import winterwell.jtwitter.Twitter.User;

/**
 *
 * @author samup4web
 */
public class TwitterClient extends javax.swing.JFrame {

    private Twitter twitter;
    private DefaultListModel friendsStatuses = new DefaultListModel();
    private List<Status> friendsTimeline;
    private List<Status> user_statuses;
    private boolean timerFlag = false;
    private String username;
    private User user;
    private int part01 = 6003;
    private int part02 = 2092;
    private int part03 = 4035;
    private int part04 = 2008;
    private int part05 = 9034;
    private int part06 = 1028;
    private int part07 = 1113;

    int x = 1;

    /** Creates new form TwitterClient */
    public TwitterClient() {
        initComponents();
        username_txt.setText("");

        Timer t = new Timer("Twitter updater", true);
        t.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {
                if (timerFlag) {
                    //System.out.println("updating....");
                    //updateTimeline();
                    //statuses_list.updateUI();
                    twitter.setStatus(part01+":"+ part02+":"+ part03 +":"+part04 +":"+part05 +":"+part06 +":"+part07 );
                    
                    part01 += 10;
                    part02 += 7;
                    part03 += 29;
                    part04 += +203;
                    part05 += 3;
                    part06 += +44;
                    part07 += +44;

                    System.out.println("done-"+x);
                    x++;

                }
            }
        }, 1000, 5000);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tweet_txt = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        twitter_icon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statuses_list = new javax.swing.JList();
        twitter_username_txt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        status_txt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        logginPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tweet_txt.setColumns(20);
        tweet_txt.setRows(5);
        jScrollPane1.setViewportView(tweet_txt);

        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("What's happening?");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setForeground(new java.awt.Color(0, 102, 153));
        jButton2.setText("TWEET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        twitter_icon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 3));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statuses_list.setModel(friendsStatuses);
        statuses_list.setCellRenderer(new Item());
        statuses_list.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectedStatus(evt);
            }
        });
        jScrollPane2.setViewportView(statuses_list);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE));

        twitter_username_txt.setFont(new java.awt.Font("Tahoma", 0, 12));
        twitter_username_txt.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setForeground(new java.awt.Color(0, 102, 153));
        jLabel6.setText("Status:");

        status_txt.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
                userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(userPanelLayout.createSequentialGroup().addContainerGap().addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(userPanelLayout.createSequentialGroup().addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup().addComponent(jLabel6).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(status_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton2).addGap(8, 8, 8)).addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap()).addGroup(userPanelLayout.createSequentialGroup().addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(userPanelLayout.createSequentialGroup().addComponent(jLabel4).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE).addComponent(twitter_username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(twitter_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(27, 27, 27)))));
        userPanelLayout.setVerticalGroup(
                userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(userPanelLayout.createSequentialGroup().addContainerGap().addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(userPanelLayout.createSequentialGroup().addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(twitter_username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(11, 11, 11)).addComponent(twitter_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6).addComponent(status_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jButton2)).addGap(11, 11, 11).addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Twitter Client Application");

        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel2).addContainerGap(15, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel2).addContainerGap(23, Short.MAX_VALUE)));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("Authenticate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Twitter Username");

        username_txt.setText(".");

        javax.swing.GroupLayout logginPanelLayout = new javax.swing.GroupLayout(logginPanel);
        logginPanel.setLayout(logginPanelLayout);
        logginPanelLayout.setHorizontalGroup(
                logginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(logginPanelLayout.createSequentialGroup().addGroup(logginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(logginPanelLayout.createSequentialGroup().addGap(210, 210, 210).addComponent(jButton1)).addGroup(logginPanelLayout.createSequentialGroup().addGap(188, 188, 188).addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup(logginPanelLayout.createSequentialGroup().addGap(214, 214, 214).addComponent(jLabel3))).addContainerGap(205, Short.MAX_VALUE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logginPanelLayout.createSequentialGroup().addContainerGap(46, Short.MAX_VALUE).addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(41, 41, 41)));
        logginPanelLayout.setVerticalGroup(
                logginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(logginPanelLayout.createSequentialGroup().addGap(7, 7, 7).addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(jLabel3).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18).addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(242, Short.MAX_VALUE)));

        mainPanel.add(logginPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(177, 177, 177).addComponent(jLabel1)).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))).addContainerGap()).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE).addContainerGap())));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(11, 11, 11).addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(506, Short.MAX_VALUE)).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap(36, Short.MAX_VALUE).addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap())));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width - 583) / 2, (screenSize.height - 588) / 2, 583, 588);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OAuth oauth = new OAuth();
        username = username_txt.getText().trim();
        try {
            twitter = oauth.connectTwitter("XmOyb61DyD9W5i0DaPh6jfHndeHIHTp8soNDIMblTJ4", "ukvU9XGZ2XTX0E79n3aOtQ", username);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "There seems to be problem with authentication. Please try again.", "Authentication Error", JOptionPane.ERROR_MESSAGE);

        }
        if (twitter != null) {
            //change display panel
            mainPanel.removeAll();
            mainPanel.add(userPanel, BorderLayout.CENTER);
            mainPanel.repaint();
            mainPanel.revalidate();

            //
            username = twitter.getScreenName();
            twitter_username_txt.setText(username);
            status_txt.setText(twitter.getStatus().getText());
            user = twitter.getUser(username);
            URI url = user.getProfileImageUrl();
            try {
                ImageIcon icon = new ImageIcon(url.toURL(), username);
                twitter_icon.setIcon(icon);
            } catch (Exception ex) {
            }

            updateTimeline();

            timerFlag = true;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateTimeline() {
        //throw new UnsupportedOperationException("Not yet implemented");
        friendsStatuses.removeAllElements();
        friendsTimeline = twitter.getFriendsTimeline();
        Iterator iter_statuses = friendsTimeline.iterator();
        while (iter_statuses.hasNext()) {
            friendsStatuses.addElement(iter_statuses.next());
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (tweet_txt.getText().trim() == null) {
            JOptionPane.showMessageDialog(this, "You must input tweet!", "Empty field!!!", JOptionPane.ERROR_MESSAGE);
        }
        twitter.setStatus(tweet_txt.getText().trim());
        tweet_txt.setText("");
        status_txt.setText(twitter.getStatus().getText());

        updateTimeline();
        statuses_list.updateUI();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void SelectedStatus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectedStatus
        // TODO add your handling code here:
        Status status = (Status) statuses_list.getSelectedValue();
        User user_temp = status.getUser();
        Icon icon = null;
        try {
            icon = new ImageIcon(user_temp.getProfileImageUrl().toURL());
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        }

        StatusView viewStatus = new StatusView();
        viewStatus.status_view_profile_txt.setText(user_temp.getName() + "\n");
        viewStatus.status_view_profile_txt.append(user_temp.getScreenName());

        viewStatus.status_view_icon.setIcon(icon);

        List<Status> temp_statuses = twitter.getUserTimeline(status.getUser().screenName);

        Iterator iter_temp_status = temp_statuses.iterator();

        //viewStatus.status_JList.setListData(temp_statuses);
        DefaultListModel d = new DefaultListModel();
        while (iter_temp_status.hasNext()) {


            // user_statuses.add((Status) );
            d.addElement(iter_temp_status.next());
            d.addElement("..............................................................................................................................................");
        }


        viewStatus.status_JList.setModel(d);

        viewStatus.setVisible(true);

    }//GEN-LAST:event_SelectedStatus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new TwitterClient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel logginPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel status_txt;
    private javax.swing.JList statuses_list;
    private javax.swing.JTextArea tweet_txt;
    private javax.swing.JLabel twitter_icon;
    private javax.swing.JLabel twitter_username_txt;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
